version: '3.4'

services:
  musicforum:
    image: bwdf64587p/music-forum:app_latest
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    ports:
      - 3000:3000
    depends_on:
      - mysql
    volumes:
      - ./upload:/usr/src/app/upload
    # volumes:
    #   - ./:/app
  mysql:
    image: bwdf64587p/music-forum:db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3366:3306
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE

volumes:
  db_data:
    driver: local
  upload_data:
    driver: local